apiVersion: v1
kind: Namespace
metadata:
  name: identity
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: identity
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:11.0.2
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "bhimA123"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_FRONTEND_URL
          value: https://identity-dev.lyceum.cloud/auth
        - name: JDBC_PARAMS
          value: "useSSL=false"
        - name: DB_VENDOR
          value: mysql
        - name: DB_ADDR
          value: rds-stg.lyceum.cloud
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: KeyCloakDB
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: bhimA123
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
