
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: microservices
  labels:
    app: goapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: goapi
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: go-service
  namespace: microservices
spec:
  selector:
    app: goapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   namespace: microservices
#   name: go-ingress
#   annotations:
#     allow.http: "true"
# spec:
#   rules:
#   #- host: dev-apps.projectsysvictor.com
#   - host: api-dev.lyceum.cloud
#     http:
#       paths:
#         - path: /api-hello
#           backend:
#             serviceName: go-service
#             servicePort: 80
